spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/excel-processing
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml